-- Não é mais necessário: a migração 0002 cria o grupo padrão e a primeira usuária do Auth vira ADMIN.
-- Mantido para referência: promover manualmente uma usuária a ADMIN.
-- update group_members set role = 'ADMIN' where user_id = (select id from auth.users where email = 'email@exemplo.com');
